#Model the actual database.yml after this:
development:
  adapter: postgresql
  host: localhost
  username: fdisk
  password: password
  database: tenure_and_promotion_development
  encoding: UTF8

production:
  adapter: postgresql
  host: localhost
  username: fdisk
  password: password
  database: tenure_and_promotion_development
  encoding: UTF8

test:
  adapter: postgresql
  host: localhost
  username: fdisk
  password: password
  database: tenure_and_promotion_test
  encoding: UTF8
